server:
  port: 8888

spring:
  application:
    name: config-service

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

  profiles:
    active: native

  cloud:
    config:
      server:
        native:
          # user.home=/Users/ing9990
          search-locations: file://${user.home}/Documents/local/native-file-repo
        git:
          default-label: master
          uri: https://github.com/ing9990/spring-cloud-config-files

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh